// Builds worker/src/voice.ts from the site's voice library.
//
//   npm run knowledge   (runs this after build-knowledge.mjs)
//
// Reads src/lib/director/voice-library.ts (exports VOICE_LINES: {id, text, tags}[]),
// bundles it with esbuild, and writes the library the Director may speak from.
// If the library file does not exist yet, an empty library is written: the worker then
// omits the `speak` tool and the voice section of the prompt, and still works (subtitles only).
import { build } from "esbuild";
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "../..");
const srcDir = join(repo, "src");
const entry = join(srcDir, "lib/director/voice-library.ts");
const out = join(here, "../src/voice.ts");

const clean = (s) => String(s).replace(/\s*\u2014\s*/g, ", ").replace(/\s+/g, " ").trim();

let lines = [];
if (!existsSync(entry)) {
  console.warn("voice: src/lib/director/voice-library.ts not found, writing an empty library (speak tool disabled)");
} else {
  const tmp = mkdtempSync(join(tmpdir(), "director-voice-"));
  try {
    const outfile = join(tmp, "voice-library.mjs");
    await build({
      entryPoints: [entry],
      outfile,
      bundle: true,
      format: "esm",
      platform: "node",
      alias: { "@": srcDir },
      logLevel: "error",
    });
    const mod = await import(pathToFileURL(outfile).href);
    const raw = mod.VOICE_LINES;
    if (!Array.isArray(raw)) throw new Error("voice-library.ts must export VOICE_LINES as an array");
    const seen = new Set();
    for (const l of raw) {
      if (!l || typeof l.id !== "string" || typeof l.text !== "string") throw new Error(`bad voice line: ${JSON.stringify(l)}`);
      if (seen.has(l.id)) throw new Error(`duplicate voice line id: ${l.id}`);
      seen.add(l.id);
      lines.push({
        id: l.id,
        text: clean(l.text),
        tags: Array.isArray(l.tags) ? l.tags.filter((t) => typeof t === "string") : [],
      });
    }
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/build-voice.mjs from src/lib/director/voice-library.ts. Do not edit; run \`npm run knowledge\`.
export type VoiceLine = { id: string; text: string; tags: string[] };

/** Lines DB recorded in his own voice. The model may only speak these, by id. */
export const VOICE_LINES: VoiceLine[] = [
${lines.map((l) => "  " + JSON.stringify(l) + ",").join("\n")}
];
`,
);
const chars = lines.reduce((n, l) => n + l.text.length + l.id.length + 4, 0);
console.log(`voice: ${lines.length} lines -> src/voice.ts (~${Math.round(chars / 4)} prompt tokens)`);
