import type { Project } from "../types";
import { SRC } from "../sources";
import { FILM_TRANSCRIPTS } from "../transcripts";

// Featured: Public Voice and the mobile origin story.
export const featuredMoreProjects: Project[] = [
  {
    slug: "public-voice",
    film: {
      src: "/films/public-voice.mp4",
      poster: "/films/public-voice.jpg",
      thumb: "/films/public-voice-thumb.jpg",
      thumb43: "/films/public-voice-thumb-43.jpg",
      vertical: { src: "/films/public-voice-vertical.mp4", poster: "/films/public-voice-vertical.jpg" },
      title: "Public Voice launch film",
      transcript: FILM_TRANSCRIPTS["public-voice"],
    },
    name: "Public Voice",
    tagline: "A voice survey that asks one smart follow-up, then lets you go.",
    year: "2026",
    role: "Technical lead",
    owned: "Technical lead: I set the technical direction and built the 2025 voice survey prototype it grew from, while two teammates wrote most of the production code.",
    org: "InnovateUS",
    featured: true,
    category: "gov-ai",
    accent: "#7C5CFF",
    problem:
      "After-course surveys return six-word answers. Interviews are rich but too slow to run after every course. InnovateUS needed something in between.",
    approach: [
      "A no-login link opens a short survey. People answer by voice or text, and every question can be skipped.",
      "When an answer is vague, an AI asks one targeted follow-up, never more than two. Then it extracts the task, the workflow, the outcome and the public benefit.",
      "Privacy is the product: no stored audio, PII redaction in the backend, and results reviewed at the cohort level.",
      "It grew from a voice survey prototype I built in July 2025 on OpenAI's realtime API. I set the technical direction while two teammates did most of the build.",
    ],
    architecture: {
      nodes: [
        "Participant browser",
        "Next.js proxy",
        "FastAPI",
        "PostgreSQL",
        "OpenAI voice and judgment",
        "PII redaction",
        "Admin dashboard",
      ],
      flow: "The browser only talks to Next.js, which proxies to FastAPI. The backend redacts PII, asks the model whether an answer is specific enough, stores structured extractions, and feeds a cohort dashboard with exports.",
    },
    outcomes: [
      {
        value: "3 min",
        numeric: 3,
        suffix: " min",
        label: "To finish a survey",
        context: "Design target from the README, not a measured median.",
        source: SRC.publicVoiceReadme,
        projectSlug: "public-voice",
      },
      {
        value: "2",
        numeric: 2,
        label: "Languages",
        context: "English and Spanish.",
        source: SRC.publicVoiceReadme,
        projectSlug: "public-voice",
      },
    ],
    stack: [
      "Next.js 16",
      "React 19",
      "Tailwind CSS",
      "FastAPI",
      "PostgreSQL",
      "SQLAlchemy",
      "OpenAI",
      "Render",
    ],
    links: [{ label: "publicvoice.innovate-us.org", href: "https://publicvoice.innovate-us.org", kind: "live" }],
    media: [
      {
        src: "/stills/public-voice/01.jpg",
        alt: "Public Voice survey question in a browser: Question 2 of 5, with the Voice tab selected and a green recording box showing a waveform and a live transcript.",
        kind: "image",
        width: 1316,
        height: 734,
        caption: "Speak instead of typing: the transcript fills in live. Illustrative sample answer.",
      },
      {
        src: "/stills/public-voice/02.jpg",
        alt: "Public Voice after the answer is confirmed. A single follow-up question appears below it, with a second recording box ready.",
        kind: "image",
        width: 1334,
        height: 640,
        caption: "One follow-up, asked only when an answer is vague. Illustrative sample.",
      },
      {
        src: "/stills/public-voice/03.jpg",
        alt: "Public Voice thank-you page with a green check and a What We Heard card summarizing the planned task.",
        kind: "image",
        width: 1384,
        height: 772,
        caption: "Then it lets you go, after showing what it heard. Illustrative sample.",
      },
      {
        src: "/stills/public-voice/04.jpg",
        alt: "Public Voice organizer dashboard showing answers grouped into three themes: Drafting, Plain language and Public comms.",
        kind: "image",
        width: 834,
        height: 726,
        caption: "The organizer view groups answers into themes. Illustrative answers, no participant data.",
      },
    ],
  },
  {
    slug: "acharya-erp",
    name: "Acharya ERP",
    tagline: "Where the shipping started: one Flutter app, thousands of students.",
    year: "2021 to 2023",
    role: "Software Engineer (Flutter)",
    owned: "I built the Flutter app and owned it from design to deployment, then trained interns to take over the codebase.",
    org: "Acharya Institutes",
    featured: true,
    category: "mobile",
    accent: "#F0997B",
    problem:
      "Students and staff at Acharya Institutes needed attendance, marks and payments in one place. The app's store rating had sunk to 1.2 stars.",
    approach: [
      "I built a cross-platform Flutter app and owned it from design to deployment.",
      "Attendance, internal assessment marks and payments (via Razorpay) run on one codebase for Android and iOS.",
      "I trained interns to take over the codebase when I moved on.",
    ],
    outcomes: [
      {
        value: "20,000+",
        numeric: 20000,
        suffix: "+",
        label: "Daily users",
        context: "Students and staff across Acharya Institutes used it every day for attendance, marks and payments.",
        source: SRC.resume,
        projectSlug: "acharya-erp",
      },
      {
        value: "1.2 to 4.5",
        label: "App store rating",
        context: "Self-reported in my resume.",
        source: SRC.resume,
        projectSlug: "acharya-erp",
      },
    ],
    stack: ["Flutter", "Dart", "Firebase", "REST APIs", "Razorpay"],
    links: [],
    media: [
      {
        src: "/stills/acharya-erp/01.jpg",
        alt: "Three screens from the Acharya ERP Flutter app: two attendance screens with per-subject percentages and absent or present dates, and a marks bar chart for Internal Assessment 2.",
        kind: "image",
        width: 1420,
        height: 820,
        caption: "Attendance and internal-assessment marks, the screens students opened every day.",
      },
      {
        src: "/stills/acharya-erp/02.jpg",
        alt: "Acharya ERP fee payment screen offering Term Fee, University Exam Fee and College Misc Fee, beside a staff self-attendance calendar with punch in and punch out times.",
        kind: "image",
        width: 880,
        height: 720,
        caption: "Fee payment for students, self-attendance for staff, on the same codebase.",
      },
      {
        src: "/stills/acharya-erp/03.jpg",
        alt: "Analytics slide from the 2022 internship deck showing Acharya ERP users by country, with India at 20K and Singapore, United States and Nepal far smaller.",
        kind: "image",
        width: 1600,
        height: 800,
        caption: "An early analytics snapshot from my 2022 internship deck, before the app reached 20,000+ daily users.",
      },
    ],
  },
];
