import type { Project } from "../types";
import { SRC } from "../sources";

const BURNES = "The Burnes Center for Social Change";

// Featured: government AI and the hackathon.
export const flagshipProjects: Project[] = [
  {
    slug: "a-iep",
    film: { src: "/films/a-iep.mp4", poster: "/films/a-iep.jpg", title: "A-IEP launch film" },
    name: "A-IEP",
    tagline: "A special-education plan, in words a parent actually uses.",
    year: "2025 to now",
    role: "Lead AI Engineer",
    owned: "Lead engineer who took the earlier co-op prototype to production: 652 of the repo's 1,263 commits, including the processing pipeline and the privacy design.",
    org: BURNES,
    featured: true,
    category: "gov-ai",
    accent: "#E8845C",
    problem:
      "An Individualized Education Program is the legal document that decides a child's support. It is dense, full of jargon and usually in English. Parents often sign it without being able to read it.",
    approach: [
      "I took the AI-EP prototype from the 2023 to 2024 co-op team and rebuilt it as a production, open source platform. I have 652 of the repo's 1,263 commits.",
      "A Step Functions pipeline runs OCR, redacts personal information with Comprehend, deletes the original upload, writes a plain-language summary in nine sections, then translates it.",
      "Privacy comes first: every stage catches into a failure handler that purges unredacted artifacts, every durable store is set to RETAIN, and infra tests assert both.",
      "Parents helped design it. We showed them the prompts and let their feedback reshape the output. Jargon words open a tap-to-define drawer, and each section points back to the original page.",
      "Quality is next. In July 2026 I audited the pipeline, found its only automated check was a schema check, and started building a synthetic IEP benchmark with a public RFC.",
    ],
    architecture: {
      nodes: [
        "Parent upload",
        "S3",
        "Step Functions",
        "Mistral OCR",
        "Comprehend PII redaction",
        "Parsing agent",
        "Translation",
        "DynamoDB",
        "React app",
      ],
      flow: "Upload, OCR, redact PII, delete the original, summarize into nine sections, translate, finalize. Any failure purges unredacted artifacts.",
    },
    outcomes: [
      {
        value: "1,000+",
        numeric: 1000,
        suffix: "+",
        label: "Families served",
        context: "Parents who have used A-IEP to understand their child's education plan, across four languages.",
        source: SRC.resume,
        projectSlug: "a-iep",
      },
      {
        value: "200+",
        numeric: 200,
        suffix: "+",
        label: "Families in the first San Francisco pilot",
        context: "Parents co-designed the tool and reported feeling more confident advocating for their children. Reported by the Burnes Center and Reboot Democracy, October 2026.",
        source: SRC.aiepSfPilot,
        projectSlug: "a-iep",
      },
      {
        value: "4",
        numeric: 4,
        label: "Languages in production",
        context: "English, Spanish, Vietnamese and Chinese. Arabic with a right-to-left UI is built and enabled outside prod.",
        source: SRC.aiepClaude,
        projectSlug: "a-iep",
      },
      {
        value: "652",
        numeric: 652,
        label: "Commits by me",
        context: "Of 1,263 in the repo, from February 2025 to October 2026, counted from git history.",
        source: "git log in /Users/db/Burnes Center Fulltime/A-IEP/ai-iep",
        projectSlug: "a-iep",
      },
      {
        value: "451",
        numeric: 451,
        label: "Jest tests green",
        context: "Plus 351 pytest and 187 vitest at the last handoff, with Playwright end-to-end runs against staging.",
        source: SRC.aiepHandoff,
        projectSlug: "a-iep",
      },
    ],
    stack: [
      "AWS CDK",
      "TypeScript",
      "Step Functions",
      "Lambda",
      "Comprehend",
      "Cognito",
      "DynamoDB",
      "S3",
      "KMS",
      "Mistral OCR",
      "OpenAI",
      "React",
      "Vite",
      "Playwright",
    ],
    links: [
      { label: "a-iep.org", href: "https://a-iep.org", kind: "live" },
      { label: "Source on GitHub", href: "https://github.com/The-Burnes-Center/a-iep", kind: "code" },
      {
        label: "Unboxing the prompt",
        href: "https://rebootdemocracy.ai/blog/unboxing-the-prompt-how-community-feedback-and-ai-helped-us-build-better-ai-together",
        kind: "press",
      },
      { label: "AI-EP at the Burnes Center", href: "https://burnes.northeastern.edu/projects/ai-ep/", kind: "doc" },
    ],
    media: [
      {
        src: "/videos/a-iep-promo.mp4",
        alt: "Promo video for A-IEP showing an IEP turned into a plain-language summary",
        kind: "video",
        width: 1920,
        height: 1080,
        caption: "A short tour of A-IEP.",
      },
      {
        src: "/media/a-iep/language-switch.jpg",
        alt: "A-IEP summary of a sample student switched into Spanish",
        kind: "image",
        width: 600,
        height: 600,
        caption: "Switch the summary into another language. Sample data.",
      },
      {
        src: "/media/a-iep/jargon-drawer.jpg",
        alt: "A-IEP jargon drawer defining the term special education",
        kind: "image",
        width: 600,
        height: 600,
        caption: "Tap any blue term for a plain definition.",
      },
      {
        src: "/media/a-iep/key-insights.jpg",
        alt: "A-IEP key insights accordion with strengths, eligibility and goals",
        kind: "image",
        width: 600,
        height: 600,
        caption: "Nine organized sections, each tied to the original page.",
      },
    ],
  },
  {
    slug: "genie",
    film: { src: "/films/genie.mp4", poster: "/films/genie.jpg", title: "GENIE launch film" },
    name: "GENIE",
    tagline: "A safe place for state employees to try generative AI.",
    year: "2024",
    role: "Co-op engineer, author of Smart Model",
    owned: "Top committer on a team build (171 of 803 commits), and the author of Smart Model, the router that picks a model for each request.",
    org: BURNES,
    featured: true,
    category: "gov-ai",
    accent: "#5DCAA5",
    problem:
      "Massachusetts state employees wanted to use generative AI, but pasting government work into a public chatbot is a security and cost problem. They needed a sandbox with guardrails.",
    approach: [
      "Built with the Executive Office of Technology Services and Security and AWS on top of the open source AWS GenAI chatbot. I am the top committer in the repo (171 of 803 commits).",
      "A chat playground, a multi-chat view that compares two to four models side by side, a task carousel of ready-made prompts, and RAG workspaces where staff upload their own documents.",
      "My own piece was Smart Model. It chooses a model for each request from the task, cost, token size and model capability, so beginners never have to know which model to pick.",
      "The sandbox also hosted the RIDE Guide and MassHealth Helper builds from the same co-op cohort.",
    ],
    architecture: {
      nodes: [
        "State employee",
        "Cognito",
        "API Gateway",
        "Lambda handlers",
        "Smart Model selector",
        "Bedrock models",
        "RAG workspaces",
        "DynamoDB",
      ],
      flow: "Sign in, send a prompt, Smart Model picks a model by task, cost and tokens, the answer streams back, and RAG workspaces ground it in uploaded documents.",
    },
    outcomes: [
      {
        value: "44,000+",
        numeric: 44000,
        suffix: "+",
        label: "State employees with access",
        context: "The Burnes Center says the sandbox enabled over 44,000 state employees to explore AI. Access, not measured daily use.",
        source: SRC.burnesBio,
        projectSlug: "genie",
      },
      {
        value: "40%",
        numeric: 40,
        suffix: "%",
        label: "Lower model spend from Smart Model",
        context: "Self-reported in my resume.",
        source: SRC.resume,
        projectSlug: "genie",
      },
      {
        value: "1",
        numeric: 1,
        label: "Governor's Citation",
        context: "Signed by Governor Healey and Lieutenant Governor Driscoll on June 26, 2024.",
        source: SRC.citation,
        projectSlug: "genie",
      },
    ],
    stack: [
      "AWS Bedrock",
      "Claude",
      "Lambda",
      "API Gateway",
      "Cognito",
      "Kendra",
      "OpenSearch",
      "DynamoDB",
      "React",
      "TypeScript",
      "Python",
    ],
    links: [
      { label: "GovTech coverage", href: SRC.govtech, kind: "press" },
      { label: "Governor's Office announcement", href: SRC.massGov, kind: "press" },
      { label: "Burnes Center profile", href: SRC.burnesBio, kind: "doc" },
    ],
    media: [
      {
        src: "/media/genie/smart-model.jpg",
        alt: "The Massachusetts AI Sandbox chat with Smart Model selected",
        kind: "image",
        width: 720,
        height: 480,
        caption: "Smart Model picks the model so you do not have to.",
      },
      {
        src: "/media/genie/multi-chat.jpg",
        alt: "Multi-chat view with Llama 3, Mixtral and Command side by side",
        kind: "image",
        width: 1152,
        height: 648,
        caption: "Multi-chat: the same prompt across several models.",
      },
      {
        src: "/photos/governors-citation.jpg",
        alt: "Governor's Citation to Dhruv Kamalesh Kumar for the InnovateMA program, June 2024",
        kind: "image",
        width: 1600,
        height: 1236,
        caption: "Governor's Citation, June 26, 2024.",
      },
    ],
  },
  {
    slug: "abe-one-l",
    film: { src: "/films/abe-one-l.mp4", poster: "/films/abe-one-l.jpg", title: "ABE and One-L launch film" },
    name: "ABE and One-L",
    tagline: "Two AI agents for state procurement. They won a national award.",
    year: "2025 to 2026",
    role: "Technical lead, ABE evaluation and observability",
    owned: "Technical lead: top committer on ABE (280 of 690 commits) and owner of its evaluation and observability; on One-L I set the direction and wrote 97 of 576 commits, with four co-op students on the build.",
    org: BURNES,
    featured: true,
    category: "gov-ai",
    accent: "#A78BFA",
    problem:
      "Massachusetts buyers wade through a thicket of purchasing rules, and lawyers redline every vendor contract against state terms by hand. Both jobs are slow and easy to get wrong.",
    approach: [
      "ABE, the Assistive Buyer Engine, is an agentic RAG chatbot. Claude on Bedrock calls four tools in a loop (knowledge base search, full-document retrieval, metadata and structured spreadsheet queries) and answers with citations.",
      "One-L takes a vendor contract through an 11-stage Step Functions workflow. It splits the document, retrieves state requirements, has Claude flag conflicts, merges the results and writes a redlined file. A human reviews every redline.",
      "I own ABE's quality loop: a RAGAS evaluation pipeline scoring faithfulness, relevancy, precision and recall, feedback that becomes test cases, and CloudWatch alarms.",
      "ABE is now a white-label template. One config file sets the brand, so another agency can rebrand and deploy it from a single file.",
      "I led the technical direction. The One-L build team was four Northeastern co-op students, and I wrote 97 of its commits.",
    ],
    architecture: {
      nodes: [
        "Buyer or lawyer",
        "CloudFront and WAF",
        "Cognito",
        "WebSocket API",
        "Chat Lambda agent loop",
        "Bedrock Claude",
        "Knowledge Base on OpenSearch Serverless",
        "DynamoDB",
        "Step Functions",
        "RAGAS eval Lambda",
        "CloudWatch",
      ],
      flow: "A question hits the agent loop, Claude calls retrieval tools and answers with citations. Contracts run through the Step Functions redline workflow. Evaluation runs score the answers and alarms watch the system.",
    },
    outcomes: [
      {
        value: "2",
        numeric: 2,
        label: "NASPO awards, 2025",
        context: "Cronin Gold and Academic Collaboration. Won by Massachusetts OSD with the Burnes Center, so I say I was part of the team behind them.",
        source: SRC.naspo,
        projectSlug: "abe-one-l",
      },
      {
        value: "83%",
        numeric: 83,
        suffix: "%",
        label: "Less legal review time",
        context: "One-L figure from my resume. OSD has not published a number, so treat it as self-reported.",
        source: SRC.resume,
        projectSlug: "abe-one-l",
      },
      {
        value: "40+",
        numeric: 40,
        suffix: "+",
        label: "CloudWatch alarms on ABE",
        context: "Current ABE README. My older resume said 8.",
        source: SRC.abeReadme,
        projectSlug: "abe-one-l",
      },
    ],
    stack: [
      "AWS CDK",
      "TypeScript",
      "Python",
      "Bedrock",
      "Claude",
      "OpenSearch Serverless",
      "Titan Embeddings",
      "Step Functions",
      "Lambda",
      "DynamoDB",
      "Cognito",
      "CloudFront",
      "RAGAS",
      "React",
    ],
    links: [
      { label: "ABE at the Burnes Center", href: "https://burnes.northeastern.edu/projects/assistive-buyers-engine-abe/", kind: "doc" },
      { label: "ABE source on GitHub", href: "https://github.com/The-Burnes-Center/ai4impact-abe-chatbot-osd", kind: "code" },
      { label: "NASPO Cronin Awards 2025", href: SRC.naspo, kind: "award" },
      { label: "NASPO Academic Collaboration", href: SRC.naspoAcademic, kind: "award" },
      { label: "Massachusetts OSD recognition", href: SRC.massGovOsd, kind: "press" },
    ],
    media: [
      {
        src: "/videos/abe-chat.mp4",
        alt: "ABE answering a question about buying under a statewide contract",
        kind: "video",
        width: 1100,
        height: 898,
        caption: "ABE answering a buyer's question. Illustrative recording.",
      },
      {
        src: "/videos/abe-eval.mp4",
        alt: "ABE quality monitoring page running a RAGAS evaluation",
        kind: "video",
        width: 1180,
        height: 858,
        caption: "A RAGAS evaluation run in the quality monitoring tab.",
      },
      {
        src: "/media/one-l-abe/abe-chat.jpg",
        alt: "ABE chat window with a procurement question and a thinking indicator",
        kind: "image",
        width: 1100,
        height: 898,
      },
      {
        src: "/media/one-l-abe/abe-eval.jpg",
        alt: "ABE quality monitoring page scoring answers with RAGAS metrics",
        kind: "image",
        width: 1180,
        height: 858,
      },
    ],
  },
  {
    slug: "vct-scout",
    film: { src: "/films/vct-scout.mp4", poster: "/films/vct-scout.jpg", title: "VCT Scout launch film" },
    name: "VCT Scout",
    tagline: "Ask in plain English, get a Valorant roster. Second place worldwide.",
    year: "2024",
    role: "Generative AI integration, prompt engineering, architecture",
    owned: "One of four on a hackathon team; I owned the generative AI layer: the tool-calling design, the system prompt that orchestrates it, and the architecture.",
    org: "AWS x Riot Games hackathon",
    featured: true,
    category: "hackathon",
    accent: "#85B7EB",
    problem:
      "Esports managers cannot read 4,700+ raw match files to build a roster. The insight is in there, but nobody has the time to dig it out.",
    approach: [
      "Four of us built it in a hackathon sprint. I owned the generative AI layer: the tool-calling design, the long system prompt that orchestrates the tools, and the architecture.",
      "Lambda and SQS convert match JSON to JSONL so Athena can query it. Claude's tool API links those tables to a Bedrock Knowledge Base of agents, abilities and gameplay.",
      "The hardest bug was Athena's 30 minute limit. We fixed it by splitting queries per tournament and building intermediate tables.",
      "A manager types something like a request for an aggressive duelist and gets a roster grounded in real stats.",
    ],
    architecture: {
      nodes: [
        "Esports manager",
        "React and Cognito",
        "API Gateway",
        "Bedrock agent with Claude",
        "Knowledge Base",
        "Athena",
        "S3 game logs",
        "Lambda and SQS ingest",
      ],
      flow: "The manager asks a question, the agent picks tools, Athena queries player tables built from 4,700+ match files, and the Knowledge Base supplies game context.",
    },
    outcomes: [
      {
        value: "2nd",
        numeric: 2,
        suffix: "nd",
        label: "Place overall",
        context: "Among more than 3,200 participants. Prize pool was $61,000 across three teams.",
        source: SRC.amazonVct,
        projectSlug: "vct-scout",
      },
      {
        value: "1",
        numeric: 1,
        label: "Best Cross-Regional Team Submission",
        context: "A separate award the team also won.",
        source: SRC.amazonVct,
        projectSlug: "vct-scout",
      },
      {
        value: "4,700+",
        numeric: 4700,
        suffix: "+",
        label: "Match files queried",
        context: "VCT Challengers data, restructured so Athena could answer in time.",
        source: SRC.devpost,
        projectSlug: "vct-scout",
      },
    ],
    stack: [
      "Amazon Bedrock",
      "Claude tool use",
      "Knowledge Bases",
      "Athena",
      "Lambda",
      "SQS",
      "API Gateway",
      "DynamoDB",
      "React",
      "Vite",
      "Cognito",
    ],
    links: [
      { label: "Devpost submission", href: SRC.devpost, kind: "doc" },
      { label: "Demo video", href: "https://vimeo.com/1026644404/ba8c799d41", kind: "video" },
      { label: "Amazon announcement", href: SRC.amazonVct, kind: "press" },
      { label: "Northeastern News", href: SRC.northeasternVct, kind: "press" },
      {
        label: "Boston Business Journal",
        href: "https://www.bizjournals.com/boston/inno/stories/news/2024/12/13/northeastern-students-place-second-gloabl-esports.html",
        kind: "press",
      },
      { label: "Code (fork)", href: "https://github.com/DB-25/vct-gen-ai", kind: "code" },
    ],
    media: [],
  },
];
