import type { Project } from "../types";
import { REPO, SRC } from "../sources";
import { FILM_TRANSCRIPTS } from "../transcripts";

const BURNES = "The Burnes Center for Social Change";

// Featured: government AI and the hackathon.
export const flagshipProjects: Project[] = [
  {
    slug: "a-iep",
    ownership: "lead",
    headlines: { problem: "Parents were signing plans they couldn’t read.", built: "A pipeline that reads the plan, so parents don’t have to decode it.", flows: "Upload in, plain language out, the original deleted.", outcomes: "Hundreds of plans, four languages." },
    film: {
      src: "/films/a-iep.mp4",
      poster: "/films/a-iep.jpg",
      thumb: "/films/a-iep-thumb.jpg",
      thumb43: "/films/a-iep-thumb-43.jpg",
      vertical: { src: "/films/a-iep-vertical.mp4", poster: "/films/a-iep-vertical.jpg" },
      title: "A-IEP launch film",
      transcript: FILM_TRANSCRIPTS["a-iep"],
    },
    name: "A-IEP",
    tagline: "A special‑education plan, in words a parent actually uses.",
    year: "2025 to now",
    role: "Lead AI Engineer",
    owned: "Lead engineer who took the earlier co-op prototype to production: 712 of the repo’s 1,266 commits, including the processing pipeline and the privacy design.",
    org: BURNES,
    featured: true,
    category: "gov-ai",
    accent: "#E8845C",
    problem:
      "An Individualized Education Program is the legal document that decides a child’s support. It is dense, full of jargon and usually in English. Parents often sign it without being able to read it.",
    approach: [
      "I took the AI-EP prototype from the 2023 to 2024 co-op team and rebuilt it as a production, open source platform.",
      "A Step Functions pipeline runs OCR, redacts personal information with Comprehend (every name included since the September 2026 change, which reaches production on 9 Oct 2026; dates kept), deletes the original upload, writes a plain-language summary in nine sections, then translates it. OCR is the one step that sees the original page; the models that summarize and translate only ever see redacted text.",
      "Privacy comes first: every stage catches into a failure handler that purges unredacted artifacts, every durable store is protected from deletion, and infrastructure tests check both.",
      "Parents helped design it. We showed them the prompts and let their feedback reshape the output. Jargon words open a tap-to-define drawer, and each section points back to the original page.",
      "Quality is next. In July 2026 I audited the pipeline and found its only automated check on output was a schema check. The evaluation design is written up in the repo: atomic-fact checks, a cross-family judge and a translation judge, projected at about $0.25 to $0.55 per document. The synthetic benchmark behind it is still being built, and no accuracy results are published yet.",
    ],
    architecture: {
      nodes: [
        "Parent upload",
        "S3",
        "Step Functions",
        "Mistral OCR",
        "Comprehend PII redaction",
        "Parsing agent",
        "Translation",
        "DynamoDB",
        "React app",
      ],
      flow: "Upload, OCR, redact PII, delete the original, summarize into nine sections, translate, finalize. Any failure purges unredacted artifacts.",
    },
    outcomes: [
      {
        value: "4",
        numeric: 4,
        label: "Languages in production",
        context: "English, Spanish, Vietnamese and Chinese are enabled in production. Arabic, with a right-to-left layout, is built and enabled on dev and staging only.",
        source: REPO.aiepLanguages,
        asOf: "5 Oct 2026",
        projectSlug: "a-iep",
      },
      {
        value: "375+",
        numeric: 375,
        suffix: "+",
        label: "IEPs processed",
        context: "Plans parents uploaded to read in plain language, in English, Spanish, Vietnamese or Chinese, from about 260 family accounts (July 2026 count).",
        source: REPO.aiepResearchLog,
        projectSlug: "a-iep",
      },
      {
        value: "200+",
        numeric: 200,
        suffix: "+",
        label: "Families in the first San Francisco pilot",
        context: "Parents co-designed the tool and reported feeling more confident advocating for their children. Reported by the Burnes Center and Reboot Democracy, October 2026.",
        source: SRC.aiepSfPilot,
        projectSlug: "a-iep",
      },
      {
        value: "712",
        numeric: 712,
        label: "Commits by me",
        context: "Of 1,266 on the public main branch, from February 2025 to October 2026, counted 5 Oct 2026. The link filters the public log by my GitHub account; 71 of the 712 carry a second author name, Dhruv Kamalesh Kumar, on the same email.",
        source: REPO.aiepMyCommits,
        projectSlug: "a-iep",
      },
      {
        value: "100",
        numeric: 100,
        label: "Test files on main",
        context: "69 TypeScript and 31 Python test files in the public repo, including the pipeline’s failure-path tests and a Playwright end-to-end suite.",
        source: REPO.aiepRepo,
        projectSlug: "a-iep",
      },
    ],
    stack: [
      "AWS CDK",
      "TypeScript",
      "Step Functions",
      "Lambda",
      "Comprehend",
      "Cognito",
      "DynamoDB",
      "S3",
      "KMS",
      "Mistral OCR",
      "OpenAI GPT-4.1",
      "React",
      "Vite",
      "Playwright",
    ],
    links: [
      { label: "a-iep.org", href: "https://a-iep.org", kind: "live" },
      { label: "Source on GitHub", href: "https://github.com/The-Burnes-Center/a-iep", kind: "code" },
      {
        label: "Unboxing the prompt",
        href: "https://rebootdemocracy.ai/blog/unboxing-the-prompt-how-community-feedback-and-ai-helped-us-build-better-ai-together",
        kind: "press",
      },
      { label: "AI-EP at the Burnes Center", href: "https://burnes.northeastern.edu/projects/ai-ep/", kind: "doc" },
    ],
    media: [
      {
        src: "/stills/a-iep/01.jpg",
        alt: "A‑IEP summary page for a sample student. An IEP Summary heading, a plain-language paragraph with the term Special education underlined as a link, and a Key Insights list with Strengths, Eligibility, Present Levels of Performance and Goals.",
        kind: "image",
        width: 1376,
        height: 684,
        caption: "The IEP, rewritten in plain language, with each hard term underlined. Sample student.",
      },
      {
        src: "/stills/a-iep/02.jpg",
        alt: "A plain definition of Special Education slides in over the IEP summary, with the dimmed plan still visible behind it. Sample student.",
        kind: "image",
        width: 960,
        height: 520,
        caption: "Tap a term and a plain definition slides in, without leaving the page.",
      },
      {
        src: "/stills/a-iep/03.jpg",
        alt: "The same A‑IEP summary switched to Spanish: the heading reads Resumen del IEP and the section reads Información Clave.",
        kind: "image",
        width: 1376,
        height: 552,
        caption: "The whole summary changes language, Spanish, Chinese and Vietnamese included. Sample data.",
      },
    ],
  },
  {
    slug: "genie",
    ownership: "core",
    headlines: { problem: "State employees wanted AI. The state wanted it safe.", built: "One sandbox, many models, and a router that picks for you.", flows: "Every request finds the right model.", outcomes: "Forty-four thousand people with access." },
    film: {
      src: "/films/genie.mp4",
      poster: "/films/genie.jpg",
      thumb: "/films/genie-thumb.jpg",
      thumb43: "/films/genie-thumb-43.jpg",
      vertical: { src: "/films/genie-vertical.mp4", poster: "/films/genie-vertical.jpg" },
      title: "GENIE launch film",
      transcript: FILM_TRANSCRIPTS["genie"],
    },
    name: "GENIE",
    tagline: "A safe place for state employees to try generative AI.",
    year: "2024",
    role: "Co‑op engineer, author of Smart Model",
    owned: "Top committer on the Burnes team’s build (171 of its 300 commits on main, after the fork from the open source AWS chatbot), and the author of Smart Model, the router that picks a model for each request.",
    org: BURNES,
    featured: true,
    category: "gov-ai",
    accent: "#5DCAA5",
    problem:
      "Massachusetts state employees wanted to use generative AI, but pasting government work into a public chatbot is a security and cost problem. They needed a sandbox with guardrails.",
    approach: [
      "Built with the Executive Office of Technology Services and Security and AWS on top of the open source AWS GenAI chatbot.",
      "A chat playground, a multi-chat view that compares two to four models side by side, a task carousel of ready-made prompts, and RAG workspaces where staff upload their own documents.",
      "My own piece was Smart Model, an LLM router. One Claude call reads each prompt beside a sheet of every model’s languages, token limits, use cases and prices, and names the model to use, so beginners never have to know which to pick.",
      "The sandbox also hosted the RIDE Guide and MassHealth Helper builds from the same co-op cohort.",
    ],
    architecture: {
      nodes: [
        "State employee",
        "Cognito",
        "API Gateway",
        "Lambda handlers",
        "Smart Model router",
        "Bedrock models",
        "RAG workspaces",
        "DynamoDB",
      ],
      flow: "Sign in, send a prompt, a Claude call picks the model from a capability sheet, the answer streams back, and RAG workspaces ground it in uploaded documents.",
    },
    outcomes: [
      {
        value: "44,000+",
        numeric: 44000,
        suffix: "+",
        label: "State employees with access",
        context: "The Burnes Center reports that the sandbox enabled over 44,000 state employees to explore AI. That is access, not measured daily use.",
        source: SRC.burnesBio,
        projectSlug: "genie",
      },
      {
        value: "40%",
        numeric: 40,
        suffix: "%",
        label: "Lower model spend from Smart Model",
        context: "The saving from routing every request through Smart Model. The baseline and the period are not published, and each routed request also pays for one router call.",
        source: SRC.resume,
        projectSlug: "genie",
      },
      {
        value: "1",
        numeric: 1,
        label: "Governor’s Citation",
        context: "Signed by Governor Healey and Lieutenant Governor Driscoll on June 26, 2024.",
        source: SRC.citation,
        projectSlug: "genie",
      },
      {
        value: "171",
        numeric: 171,
        label: "Commits by me on the team build",
        context: "Of the 300 commits the Burnes team made on main after forking the open source AWS GenAI chatbot. The other 503 of the repo’s 803 are that upstream history. Two authors made the 300: me (171) and a teammate (129). Private repo, counted 5 Oct 2026.",
        source: SRC.genieGit,
        projectSlug: "genie",
      },
    ],
    stack: [
      "AWS Bedrock",
      "Claude",
      "Lambda",
      "API Gateway",
      "Cognito",
      "Kendra",
      "OpenSearch",
      "DynamoDB",
      "React",
      "TypeScript",
      "Python",
    ],
    links: [
      { label: "GovTech coverage", href: SRC.govtech, kind: "press" },
      { label: "Governor’s Office announcement", href: SRC.massGov, kind: "press" },
      { label: "Burnes Center profile", href: SRC.burnesBio, kind: "doc" },
    ],
    media: [
      {
        src: "/stills/genie/01.jpg",
        alt: "GENIE multi-chat: one prompt asking for a LinkedIn post about a bill, sent to Llama 3 70B Instruct, Mixtral 8x7B Instruct and Command in three side-by-side columns, each with its own answer.",
        kind: "image",
        width: 1600,
        height: 712,
        caption: "Multi-chat: one prompt, three models, side by side. Answers shown are illustrative.",
      },
      {
        src: "/stills/genie/02.jpg",
        alt: "The GENIE prompt box with a typed request, a Smart Model selector and a workspace selector set to No workspace.",
        kind: "image",
        width: 1472,
        height: 240,
        caption: "One prompt box. Leave it on Smart Model, or pick a workspace to ground the answer in state data.",
      },
      {
        src: "/stills/genie/03.jpg",
        alt: "Diagram of Smart Model routing: a request goes through a check of task, cost and token size, and Mixtral 8x7B Instruct is highlighted as the chosen model.",
        kind: "image",
        width: 1600,
        height: 376,
        caption: "How Smart Model picks a model: by task, cost and token size. A schematic, not a recording.",
      },
    ],
  },
  {
    slug: "abe-one-l",
    ownership: "lead",
    headlines: { problem: "Procurement runs on rules nobody can keep in their head.", built: "Two agents: one answers buyers, one redlines contracts.", flows: "Questions get citations. Contracts get redlines.", outcomes: "Two NASPO awards, and lawyers who start from a draft." },
    film: {
      src: "/films/abe-one-l.mp4",
      poster: "/films/abe-one-l.jpg",
      thumb: "/films/abe-one-l-thumb.jpg",
      thumb43: "/films/abe-one-l-thumb-43.jpg",
      vertical: { src: "/films/abe-one-l-vertical.mp4", poster: "/films/abe-one-l-vertical.jpg" },
      title: "ABE and One-L launch film",
      transcript: FILM_TRANSCRIPTS["abe-one-l"],
    },
    name: "ABE and One-L",
    tagline: "Two AI agents for state procurement, recognized by NASPO in 2025.",
    year: "2025 to 2026",
    role: "Technical lead, ABE evaluation and observability",
    owned: "Joined One‑L in November 2025 and ABE in February 2026, after the 2025 NASPO awards. Top committer on ABE since (270 of 678 commits on main), where I built the quality monitoring, the thumbs-up-to-test-case pipeline and the alarms; on One‑L I set the direction (98 of 576 commits on main).",
    org: BURNES,
    featured: true,
    category: "gov-ai",
    accent: "#A78BFA",
    problem:
      "Massachusetts buyers wade through a thicket of purchasing rules, and lawyers redline every vendor contract against state terms by hand. Both jobs are slow and easy to get wrong.",
    approach: [
      "ABE, the Assistive Buyer Engine, is an agentic RAG chatbot. Claude on Bedrock calls four tools in a loop (knowledge base search, full-document retrieval, metadata and structured spreadsheet queries) and answers with citations.",
      "One‑L takes a vendor contract through an 11-stage Step Functions workflow. It splits the document, retrieves state requirements, has Claude 4 Sonnet flag conflicts, merges the results and writes a redlined file. A human reviews every redline.",
      "Both agents won NASPO awards in 2025, before I joined: I picked up One‑L in November 2025 and ABE in February 2026. I own ABE’s quality loop today. A teammate, Ritik Bompilwar, wrote the first RAGAS pipeline in 2025. From February 2026 I built the quality-monitoring platform around it, added the path that turns thumbs-up answers into test cases, and built the CloudWatch alarms.",
      "ABE is now a white-label template. One config file sets the brand, so another agency can rebrand and deploy it from a single file.",
      "I have set the technical direction for One‑L since November 2025, working with the four Northeastern co-op students on the team.",
    ],
    architecture: {
      nodes: [
        "Buyer or lawyer",
        "CloudFront and WAF",
        "Cognito",
        "WebSocket API",
        "Chat Lambda agent loop",
        "Bedrock Claude",
        "Knowledge Base on OpenSearch Serverless",
        "DynamoDB",
        "Step Functions",
        "RAGAS eval Lambda",
        "CloudWatch",
      ],
      flow: "A question hits the agent loop, Claude calls retrieval tools and answers with citations. Contracts run through the Step Functions redline workflow. Evaluation runs score the answers and alarms watch the system.",
      lanes: [
        {
          name: "ABE",
          nodes: [
            "Buyer",
            "CloudFront and WAF",
            "Cognito",
            "WebSocket API",
            "Chat Lambda agent loop",
            "Bedrock Claude",
            "Knowledge Base on OpenSearch Serverless",
            "RAGAS eval Lambda",
            "CloudWatch",
          ],
        },
        {
          name: "One-L",
          nodes: ["Lawyer", "Cognito", "Step Functions redline workflow", "Bedrock Claude", "Knowledge Base on OpenSearch Serverless", "Redlined contract"],
        },
      ],
    },
    outcomes: [
      {
        value: "2",
        numeric: 2,
        label: "NASPO awards for ABE and One‑L, 2025",
        context: "Cronin Gold and Academic Collaboration, won by Massachusetts OSD with the Burnes Center before I joined either project. I now lead ABE’s quality monitoring and One‑L’s direction.",
        source: SRC.naspo,
        projectSlug: "abe-one-l",
      },
      {
        value: "83%",
        numeric: 83,
        suffix: "%",
        label: "Less legal review time",
        context: "From my résumé: lawyers review a redline that One‑L has already drafted, instead of marking up each contract by hand. The baseline and sample are not published here.",
        source: SRC.resume,
        projectSlug: "abe-one-l",
      },
      {
        value: "43",
        numeric: 43,
        label: "CloudWatch alarms on ABE",
        context: "Operations alarms: errors and throttles on ten Lambdas, read and write throttles on nine tables, and five more (chat latency, HTTP 4xx and 5xx, no WebSocket connections, evaluation workflow failures). None watches answer quality. A web application firewall and X-Ray tracing sit alongside.",
        source: REPO.abeReadme,
        asOf: "5 Oct 2026",
        projectSlug: "abe-one-l",
      },
      {
        value: "270",
        numeric: 270,
        label: "Commits by me on ABE",
        context: "Of 678 on the public main branch, from my first commit on 10 Feb 2026, counted 5 Oct 2026. Two of the 270 carry a second author name, Dhruv Kamalesh Kumar, on the same email.",
        source: REPO.abeMyCommits,
        projectSlug: "abe-one-l",
      },
      {
        value: "98",
        numeric: 98,
        label: "Commits by me on One‑L",
        context: "Of 576 on main, from my first commit on 29 Nov 2025, counted 5 Oct 2026. The repo is private, so this count cannot be checked from here.",
        source: SRC.oneLGit,
        projectSlug: "abe-one-l",
      },
    ],
    stack: [
      "AWS CDK",
      "TypeScript",
      "Python",
      "Bedrock",
      "Claude",
      "OpenSearch Serverless",
      "Titan Embeddings",
      "Step Functions",
      "Lambda",
      "DynamoDB",
      "Cognito",
      "CloudFront",
      "RAGAS",
      "React",
    ],
    links: [
      { label: "ABE at the Burnes Center", href: "https://burnes.northeastern.edu/projects/assistive-buyers-engine-abe/", kind: "doc" },
      { label: "ABE source on GitHub", href: "https://github.com/The-Burnes-Center/ai4impact-abe-chatbot-osd", kind: "code" },
      { label: "NASPO Cronin Awards 2025", href: SRC.naspo, kind: "award" },
      { label: "NASPO Academic Collaboration", href: SRC.naspoAcademic, kind: "award" },
      { label: "Massachusetts OSD recognition", href: SRC.massGovOsd, kind: "press" },
    ],
    media: [
      {
        src: "/stills/abe-one-l/01.jpg",
        alt: "ABE chat answering how to make a purchase under a Statewide Contract, with three steps, numbered citations and a list of three source documents with page numbers.",
        kind: "image",
        width: 1056,
        height: 800,
        caption: "ABE answers a buyer’s question with citations back to the source documents. Illustrative recording.",
      },
      {
        src: "/stills/abe-one-l/02.jpg",
        alt: "ABE Quality Monitoring page showing Answer, Retrieval and Response quality scores and a per-question table of RAGAS metrics.",
        kind: "image",
        width: 1136,
        height: 750,
        caption: "Quality monitoring: every answer is scored with RAGAS metrics. Sample data.",
      },
      {
        src: "/stills/abe-one-l/03.jpg",
        alt: "One‑L contract review window. Two clauses in a vendor agreement are struck through with replacement wording in green, beside a five-step checklist ending in human review.",
        kind: "image",
        width: 1228,
        height: 936,
        caption: "One‑L flags conflicting clauses and drafts the redline. A person reviews every one. Invented sample contract.",
      },
    ],
  },
  {
    slug: "vct-scout",
    ownership: "core",
    headlines: { problem: "Scouting a pro roster means drowning in match data.", built: "An agent that turns one sentence into a five-player roster.", flows: "Plain English in, tool calls out, a roster back.", outcomes: "Second out of 3,200+ participants." },
    film: {
      src: "/films/vct-scout.mp4",
      poster: "/films/vct-scout.jpg",
      thumb: "/films/vct-scout-thumb.jpg",
      thumb43: "/films/vct-scout-thumb-43.jpg",
      vertical: { src: "/films/vct-scout-vertical.mp4", poster: "/films/vct-scout-vertical.jpg" },
      title: "VCT Scout launch film",
      transcript: FILM_TRANSCRIPTS["vct-scout"],
    },
    name: "VCT Scout",
    tagline: "Ask in plain English, get a Valorant roster. Second place worldwide.",
    year: "2024",
    role: "Generative AI layer: system prompt and tool design",
    owned: "One of four on a hackathon team. I designed the agent’s tool calling and wrote the system prompt that orchestrates it, plus the tools that save and load a team composition; teammates built the chat backend, the player-data tools and the map tools.",
    org: "AWS x Riot Games hackathon",
    featured: true,
    category: "hackathon",
    accent: "#85B7EB",
    problem:
      "Esports managers cannot read 4,700+ raw match files to build a roster. The insight is in there, but nobody has the time to dig it out.",
    approach: [
      "Four of us built it in a hackathon sprint on Amazon Bedrock.",
      "Lambda and SQS convert match JSON to JSONL so Athena can query it. Claude’s tool API links those tables to a Bedrock Knowledge Base of agents, abilities and gameplay.",
      "The hardest bug was Athena’s 30 minute limit. We fixed it by splitting queries per tournament and building intermediate tables.",
      "A manager types something like a request for an aggressive duelist and gets a roster grounded in real stats.",
      "My layer sits on top: the system prompt that says when to call which tool and how to present a roster, and tools that save and fetch a versioned team composition, so a follow-up question edits the roster instead of rebuilding it.",
    ],
    architecture: {
      nodes: [
        "Esports manager",
        "React and Cognito",
        "API Gateway",
        "Claude tool-use loop on Bedrock",
        "Knowledge Base",
        "Athena",
        "S3 game logs",
        "Lambda and SQS ingest",
      ],
      flow: "The manager asks a question, Claude picks tools, typed arguments become Athena queries over player tables built from 4,700+ match files, and the Knowledge Base supplies game context.",
    },
    outcomes: [
      {
        value: "2nd",
        numeric: 2,
        suffix: "nd",
        label: "Place overall",
        context: "Among more than 3,200 participants. Prize pool was $61,000 across three teams.",
        source: SRC.amazonVct,
        projectSlug: "vct-scout",
      },
      {
        value: "1",
        numeric: 1,
        label: "Best Cross‑Regional Team Submission",
        context: "A separate award the team also won.",
        source: SRC.amazonVct,
        asOf: "Dec 2024",
        projectSlug: "vct-scout",
      },
      {
        value: "4,700+",
        numeric: 4700,
        suffix: "+",
        label: "Match files queried",
        context: "The size of the data the team restructured so Athena could answer in time, not a measure of accuracy.",
        source: SRC.devpost,
        asOf: "2024",
        projectSlug: "vct-scout",
      },
    ],
    stack: [
      "Amazon Bedrock",
      "Claude tool use",
      "Knowledge Bases",
      "Athena",
      "Lambda",
      "SQS",
      "API Gateway",
      "DynamoDB",
      "React",
      "Vite",
      "Cognito",
    ],
    links: [
      { label: "Devpost submission", href: SRC.devpost, kind: "doc" },
      { label: "Demo video", href: "https://vimeo.com/1026644404/ba8c799d41", kind: "video" },
      { label: "Amazon announcement", href: SRC.amazonVct, kind: "press" },
      { label: "Northeastern News", href: SRC.northeasternVct, kind: "press" },
      {
        label: "Boston Business Journal",
        href: "https://www.bizjournals.com/boston/inno/stories/news/2024/12/13/northeastern-students-place-second-gloabl-esports.html",
        kind: "press",
      },
      { label: "Code (fork)", href: "https://github.com/DB-25/vct-gen-ai", kind: "code" },
    ],
    media: [
      {
        src: "/stills/vct-scout/01.jpg",
        alt: "VCT Scout mid-request: the prompt is a red bubble, and under the agent's reply it lists its own tool calls, Data Retrieval, Data Analysis and Team Composition.",
        kind: "image",
        width: 930,
        height: 295,
        caption: "The agent chooses its own tools: retrieve data, analyze it, compose a team.",
      },
      {
        src: "/stills/vct-scout/02.jpg",
        alt: "Five VCT Scout roster cards in a row: Boaster on Omen, aspas on Jett, MaKo on Viper, Derke on Raze and Feniz on Cypher, each with an agent portrait and kills, deaths and games.",
        kind: "image",
        width: 1550,
        height: 344,
        caption: "The roster it builds: five players, their roles and real kills, deaths and games.",
      },
      {
        src: "/stills/vct-scout/03.jpg",
        alt: "VCT Scout after a follow-up question. The agent lists its tool calls, explains why Feniz replaces Chronicle as the Cypher player, and the team formation panel shows the updated roster cards.",
        kind: "image",
        width: 1276,
        height: 896,
        caption: "Ask a follow-up in plain English and the agent revises the roster from real player stats.",
      },
    ],
  },
];
