import type { Project } from "../types";
import { SRC } from "../sources";
import { FILM_TRANSCRIPTS } from "../transcripts";

const BURNES = "The Burnes Center for Social Change";

// Platform, tools and lab work. Not featured.
export const moreProjects: Project[] = [
  {
    slug: "knowledge-agent-for-impact",
    name: "knowledge-agent-for-impact",
    tagline: "The shared RAG stack behind many AI for Impact chatbots.",
    year: "2024 to 2026",
    role: "Technical lead for the platform",
    org: BURNES,
    featured: false,
    category: "platform",
    accent: "#C4B5FD",
    problem:
      "Every agency chatbot needed the same plumbing: auth, a vector store, ingestion, citations and monitoring. Rebuilding it per project wasted a cohort of student time.",
    approach: [
      "A reusable AWS CDK stack with OpenSearch Serverless, Lambda, DynamoDB and Cognito, so a new chatbot starts from a working base.",
      "My job was the technical direction across the program: reviewing architectures, setting the RAG and evaluation patterns, and mentoring the student engineers who deployed it.",
    ],
    architecture: {
      nodes: ["React app", "Cognito", "API Gateway", "Lambda", "OpenSearch Serverless", "Bedrock", "DynamoDB"],
      flow: "Documents are chunked into OpenSearch, a Lambda retrieves and prompts the model, and Cognito gates every call.",
    },
    outcomes: [
      {
        value: "10+",
        numeric: 10,
        suffix: "+",
        label: "Production deployments",
        context: "Deployed across AI for Impact projects. I was technical lead for the platform, alongside the engineers who built it.",
        source: SRC.resume,
        projectSlug: "knowledge-agent-for-impact",
      },
    ],
    stack: ["AWS CDK", "TypeScript", "Python", "OpenSearch Serverless", "Lambda", "DynamoDB", "Cognito"],
    links: [{ label: "AI for Impact program", href: SRC.aiForImpact, kind: "doc" }],
    media: [],
  },
  {
    slug: "coaching-tool",
    name: "Public Engagement Coach",
    tagline: "A coach that turns a rough idea into a public engagement plan.",
    year: "2026",
    role: "Technical lead",
    org: "InnovateUS and The GovLab",
    featured: false,
    category: "gov-ai",
    accent: "#85B7EB",
    problem:
      "Practitioners who run public engagement projects rarely have an expert to ask. The GovLab framework is good, but it is a PDF.",
    approach: [
      "A chat that walks people through the nine-question framework, with an orchestrator that routes each message to a coaching, retrieval or suggestion agent.",
      "Answers draw on a curated case-study library and anonymized expert interviews in Weaviate, and end with an evidence-grounded reflection.",
    ],
    architecture: {
      nodes: ["React SPA", "CloudFront", "Lambda orchestrator", "Weaviate", "OpenAI", "DynamoDB"],
      flow: "Each message is classified, sent to the matching agent, grounded by hybrid search, and streamed back.",
    },
    outcomes: [
      {
        value: "9",
        numeric: 9,
        label: "Framework questions",
        context: "The GovLab nine-question framework the coach is built around.",
        source: SRC.coachReadme,
        projectSlug: "coaching-tool",
      },
    ],
    stack: ["React", "Vite", "AWS Lambda", "CloudFront", "CDK", "Weaviate", "OpenAI"],
    links: [{ label: "coach.innovate-us.org", href: "https://coach.innovate-us.org", kind: "live" }],
    media: [],
  },
  {
    slug: "course-delivery",
    name: "Course Delivery SMS",
    tagline: "An 8‑day video course that nudges you by text.",
    year: "2026",
    role: "Sole engineer",
    owned: "Sole engineer: all 65 commits, from the Lambda API and SMS pacing to the quiz gate and the certificate.",
    org: "InnovateUS",
    featured: false,
    category: "platform",
    accent: "#F6C453",
    problem:
      "Self-paced online courses lose learners early. The InnovateUS Civic AI course needed a gentle nudge that learners could not mistake for spam.",
    approach: [
      "Learners sign in with a texted one-time code, watch one video a day, pass a one-question quiz, and download a personalized certificate.",
      "A quiet reminder goes out after 24 hours of inactivity, at most once a day, between 9am and 8pm local time, with a link back to the exact spot.",
      "Texts go out over AWS End User Messaging from a registered 10DLC number. Email signups use SES with suppression lists and one-click unsubscribe.",
      "I also wrote the runbook, the SMS compliance doc and the admin console.",
    ],
    architecture: {
      nodes: ["React site", "CloudFront", "API Gateway", "Hono on Lambda", "DynamoDB", "EventBridge", "End User Messaging SMS", "SES"],
      flow: "An hourly EventBridge pass finds inactive learners and sends one reminder over SMS or email. Progress heartbeats let people resume on any device.",
    },
    outcomes: [
      {
        value: "8",
        numeric: 8,
        label: "Lessons, one a day",
        context: "One chapter a day across the InnovateUS Civic AI course.",
        source: SRC.courseReadme,
        projectSlug: "course-delivery",
      },
    ],
    stack: ["Hono", "AWS Lambda", "AWS CDK", "DynamoDB", "EventBridge", "End User Messaging SMS", "SES", "React", "Vite"],
    links: [],
    media: [],
  },
  {
    slug: "arc-control-mcp",
    film: {
      src: "/films/arc-control-mcp.mp4",
      poster: "/films/arc-control-mcp.jpg",
      thumb: "/films/arc-control-mcp-thumb.jpg",
      thumb43: "/films/arc-control-mcp-thumb-43.jpg",
      vertical: { src: "/films/arc-control-mcp-vertical.mp4", poster: "/films/arc-control-mcp-vertical.jpg" },
      title: "arc-control-mcp launch film",
      transcript: FILM_TRANSCRIPTS["arc-control-mcp"],
    },
    name: "arc-control-mcp",
    tagline: "An MCP server that lets agents drive the Arc browser.",
    year: "2026",
    role: "Creator",
    featured: false,
    category: "tool",
    accent: "#8B5CF6",
    problem:
      "The bundled Chrome MCP server cannot be pointed at Arc, and Arc’s scripting dictionary differs from Chrome’s in exactly the places that matter.",
    approach: [
      "26 tools in six modules read pages, click, fill forms and run JavaScript over Apple Events, using the browser I am already signed in to.",
      "The server keeps its own tabs separate from mine, refuses to touch the tab I am looking at, and reports which permissions are missing instead of failing silently.",
      "One runtime dependency, no build step, CI, and a changelog and security policy.",
    ],
    outcomes: [
      {
        value: "26",
        numeric: 26,
        label: "Tools",
        context: "In six modules.",
        source: SRC.arcReadme,
        projectSlug: "arc-control-mcp",
      },
      {
        value: "100",
        numeric: 100,
        label: "npm downloads, last month",
        context: "Month ending October 1, 2026.",
        source: SRC.arcNpm,
        projectSlug: "arc-control-mcp",
      },
    ],
    stack: ["Node.js", "MCP SDK", "JXA", "Apple Events", "GitHub Actions"],
    links: [
      { label: "GitHub", href: "https://github.com/DB-25/arc-control-mcp", kind: "code" },
      { label: "npm", href: "https://www.npmjs.com/package/arc-control-mcp", kind: "code" },
    ],
    media: [],
  },
  {
    slug: "voice-survey-agent",
    compact: true,
    name: "Voice Survey Agent",
    tagline: "The prototype that became Public Voice.",
    year: "2025",
    role: "Creator",
    featured: false,
    category: "lab",
    accent: "#7C5CFF",
    problem: "Could a short voice conversation replace a text box for workshop follow-up surveys?",
    approach: [
      "A Next.js app that runs a follow-up survey over OpenAI’s realtime voice API, with multiple choice and long-text questions and progress tracking.",
      "It answered the question, then the idea moved into Public Voice with privacy, dashboards and exports.",
    ],
    outcomes: [
      {
        value: "3 days",
        label: "First commit to last push",
        context: "Created July 15, 2025, last pushed July 18, 2025.",
        source: "https://github.com/DB-25/voice-based-survey-agent",
        projectSlug: "voice-survey-agent",
      },
    ],
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "OpenAI Realtime API"],
    links: [{ label: "GitHub", href: "https://github.com/DB-25/voice-based-survey-agent", kind: "code" }],
    media: [],
  },
  {
    slug: "vedira",
    compact: true,
    name: "Vedira",
    tagline: "A Flutter app for AI‑generated lessons.",
    year: "2025",
    role: "Mobile developer",
    featured: false,
    category: "mobile",
    accent: "#F0997B",
    problem: "People who want to learn something specific get generic courses.",
    approach: [
      "A cross-platform Flutter front end for personalized, scheduled AI-generated lessons.",
      "It talks to a serverless AWS Lambda backend written by a teammate, Rudra Sett.",
    ],
    outcomes: [
      {
        value: "2",
        numeric: 2,
        label: "Platforms",
        context: "iOS through TestFlight and Android through APK.",
        source: "https://github.com/DB-25/vedira",
        projectSlug: "vedira",
      },
    ],
    stack: ["Flutter", "Dart", "AWS Lambda"],
    links: [{ label: "GitHub", href: "https://github.com/DB-25/vedira", kind: "code" }],
    media: [],
  },
  {
    slug: "plastic-usage-classification",
    compact: true,
    name: "Plastic Usage Classification",
    tagline: "Computer vision coursework: sorting plastic into four categories from a photo.",
    year: "2023",
    role: "Author",
    org: "Northeastern University",
    featured: false,
    category: "lab",
    accent: "#5DCAA5",
    problem: "Can a model tell which of four plastic categories a product belongs to from its picture alone?",
    approach: [
      "PyTorch classifier with a ResNet50 backbone and an MLP head, tuned with Optuna.",
      "A Northeastern course project, built with one other contributor.",
    ],
    outcomes: [
      {
        value: "88.77%",
        numeric: 88.77,
        suffix: "%",
        label: "F1 score",
        context: "Across four plastic categories, from the product photo alone. The code is public.",
        source: SRC.interviewNotes,
        projectSlug: "plastic-usage-classification",
      },
    ],
    stack: ["Python", "PyTorch", "ResNet50", "Optuna"],
    links: [{ label: "GitHub", href: "https://github.com/DB-25/plastic_usage_classification", kind: "code" }],
    media: [],
  },
  {
    slug: "wesource-fraud-detection",
    compact: true,
    name: "Delivery Fraud Detector",
    tagline: "A small CNN for a delivery startup.",
    year: "2021 to 2022",
    role: "Machine Learning Intern",
    org: "We Source Company",
    featured: false,
    category: "lab",
    accent: "#85B7EB",
    problem: "A delivery company was losing money to fraudulent deliveries.",
    approach: [
      "I trained a CNN-based fraud detector and built two Flutter delivery apps in the same internship.",
    ],
    outcomes: [
      {
        value: "87.34%",
        numeric: 87.34,
        suffix: "%",
        label: "Accuracy",
        context: "At 103 ms latency.",
        source: SRC.resume,
        projectSlug: "wesource-fraud-detection",
      },
    ],
    stack: ["Python", "TensorFlow", "Flutter"],
    links: [],
    media: [],
  },
];
