import type { Project } from "../types";
import { REPO, SRC } from "../sources";
import { FILM_TRANSCRIPTS } from "../transcripts";

const BURNES = "The Burnes Center for Social Change";

// Platform, tools and lab work. Not featured.
export const moreProjects: Project[] = [
  {
    slug: "knowledge-agent-for-impact",
    compact: true,
    ownership: "advisor",
    name: "knowledge-agent-for-impact",
    tagline: "The shared RAG stack behind AI for Impact chatbots. Technical direction and review; student engineers built it.",
    year: "2024 to 2026",
    role: "Technical direction for the platform",
    org: BURNES,
    featured: false,
    category: "platform",
    accent: "#C4B5FD",
    problem:
      "Every agency chatbot needed the same plumbing: auth, a vector store, ingestion, citations and monitoring. Rebuilding it per project wasted a cohort of student time.",
    approach: [
      "A reusable AWS CDK stack with an Amazon Kendra index, Lambda, DynamoDB and Cognito, so a new chatbot starts from a working base.",
      "My job was the technical direction across the program: reviewing architectures, setting the RAG and evaluation patterns, and mentoring the student engineers who deployed it.",
    ],
    architecture: {
      nodes: ["React app", "Cognito", "WebSocket API", "Chat Lambda", "Amazon Kendra", "Bedrock", "DynamoDB"],
      flow: "Documents land in S3 and sync into a Kendra index. A chat Lambda retrieves passages over a WebSocket, prompts the model and streams the answer, and Cognito gates every call.",
    },
    outcomes: [],
    stack: ["AWS CDK", "TypeScript", "Python", "Amazon Kendra", "Lambda", "DynamoDB", "Cognito"],
    links: [{ label: "AI for Impact program", href: SRC.aiForImpact, kind: "doc" }],
    media: [
      {
        src: "/stills/knowledge-agent-for-impact/01.jpg",
        alt: "Architecture diagram of the knowledge-agent-for-impact AWS stack. A browser reaches a CloudFront-served S3 website, a WebSocket API and an HTTP API behind Cognito. Lambda functions for chat, Kendra sync, file handling, sessions and feedback read and write Bedrock, a Kendra index, S3 buckets and two DynamoDB tables.",
        kind: "image",
        width: 1600,
        height: 770,
        caption: "Architecture, drawn from the CDK stack.",
      },
    ],
  },
  {
    slug: "coaching-tool",
    ownership: "lead",
    name: "Public Engagement Coach",
    tagline: "A coach that turns a rough idea into a public engagement plan.",
    year: "2026",
    role: "Technical lead",
    org: "InnovateUS and The GovLab",
    featured: false,
    category: "gov-ai",
    accent: "#85B7EB",
    problem:
      "Practitioners who run public engagement projects rarely have an expert to ask. The GovLab framework is good, but it is a PDF.",
    approach: [
      "A chat that walks people through the nine-question framework, with an orchestrator that routes each message to a coaching, retrieval or suggestion agent.",
      "Answers draw on a curated case-study library and anonymized expert interviews in Weaviate, and end with an evidence-grounded reflection.",
    ],
    architecture: {
      nodes: ["React SPA", "CloudFront", "Lambda orchestrator", "Weaviate", "OpenAI", "DynamoDB"],
      flow: "Each message is classified, sent to the matching agent, grounded by hybrid search, and streamed back.",
    },
    outcomes: [
      {
        value: "9",
        numeric: 9,
        label: "Framework questions",
        context: "The GovLab nine-question framework the coach is built around.",
        source: SRC.coachReadme,
        asOf: "12 Jun 2026",
        projectSlug: "coaching-tool",
      },
    ],
    stack: ["React", "Vite", "AWS Lambda", "CloudFront", "CDK", "Weaviate", "OpenAI"],
    links: [{ label: "coach.innovate-us.org", href: "https://coach.innovate-us.org", kind: "live" }],
    media: [
      {
        src: "/stills/coaching-tool/01.jpg",
        alt: "The Public Engagement Coach landing page on coach.innovate-us.org: a blue hero reading The Public Engagement Coach, a short description, and Get Started and Learn More buttons.",
        kind: "image",
        width: 1600,
        height: 662,
        caption: "The landing page at coach.innovate-us.org, captured live.",
      },
      {
        src: "/stills/coaching-tool/02.jpg",
        alt: "A chat in the Public Engagement Coach. A user asks how to engage non-native English speakers in their community. The coach answers with a short recommendation and a follow-up question, with two case studies listed as sources.",
        kind: "image",
        width: 1600,
        height: 550,
        caption: "The coach answers with cited case studies and asks one follow-up. A frame from the tour video on the live site.",
      },
      {
        src: "/stills/coaching-tool/03.jpg",
        alt: "The Case Study Library page of the Public Engagement Coach, with search, scale, topic and country filters, and an open case study on citizen conferences about health policy in Bavaria with key outcomes and implementation steps.",
        kind: "image",
        width: 1600,
        height: 1266,
        caption: "The case study library the coach retrieves from, captured live.",
      },
    ],
  },
  {
    slug: "course-delivery",
    ownership: "sole",
    headlines: {
      problem: "A free course only works if people come back.",
      built: "An 8‑day course that texts you the way back.",
      flows: "Two paths: the lesson you take, and the reminder you might get.",
      outcomes: "Built in three days, not public yet.",
    },
    film: {
      src: "/films/course-delivery.mp4",
      poster: "/films/course-delivery.jpg",
      thumb: "/films/course-delivery-thumb.jpg",
      thumb43: "/films/course-delivery-thumb-43.jpg",
      vertical: { src: "/films/course-delivery-vertical.mp4", poster: "/films/course-delivery-vertical.jpg" },
      title: "Civic AI Course Delivery launch film",
      transcript: FILM_TRANSCRIPTS["course-delivery"],
    },
    name: "Civic AI Course Delivery",
    tagline: "An 8‑day, SMS‑paced course platform for InnovateUS Civic AI.",
    year: "2026",
    role: "Sole engineer",
    owned:
      "Sole engineer, start to finish in three days: sign‑in, SMS pacing, the quiz gate, certificate, admin console, runbook and the carrier compliance doc.",
    org: "InnovateUS",
    featured: true,
    category: "platform",
    accent: "#F6C453",
    problem:
      "Self-paced online courses lose learners early. The InnovateUS Civic AI course needed a gentle nudge that nobody would mistake for spam, and a real check that a lesson was watched, not just opened.",
    approach: [
      "Learners sign up with a name and a mobile number or email, confirm with a six-digit code, and watch one video lesson a day. A one-question quiz gates each next lesson, and a personalized PDF certificate follows lesson eight.",
      "Skipping ahead does not count. The player reports which seconds were actually seen, and the question unlocks at about 90 percent coverage, so dragging the scrubber to the end changes nothing.",
      "Reminders follow strict rules: 24 hours of inactivity, at most one a day, 9 am to 8 pm in the learner's time zone, only in the first 8 days, and never more than two unanswered in a row. Each text starts with \"InnovateUS:\", fits one segment, and carries a short link on the course's own domain that drops the learner back where they stopped.",
      "Texts leave from the course's own 10DLC number through AWS End User Messaging. STOP, START and HELP are handled and delivery failures are classified. Email sign-ups get the same limits through SES, with a suppression list, one-click unsubscribe and a service-wide send cap.",
      "Around the learner flow: an admin console and API, a Turnstile bot check on sign-in, a WAF rate limit on admin sign-in, two CDK stacks (dev and prod) with alarms and a manual CI deploy, and five docs (SMS, email, runbook, admin API, copy deck). It is pre-launch: there is no public URL yet.",
    ],
    architecture: {
      nodes: [
        "Texted link",
        "CloudFront",
        "React site",
        "API Gateway",
        "Hono on Lambda",
        "DynamoDB",
        "EventBridge",
        "Scheduler Lambda",
        "End User Messaging SMS",
        "SES",
      ],
      lanes: [
        { name: "Learner path", nodes: ["Texted link", "CloudFront", "React site", "API Gateway", "Hono on Lambda", "DynamoDB"] },
        { name: "Reminder path", nodes: ["EventBridge, hourly", "Scheduler Lambda", "Send rules", "SMS or SES email", "Short link back"] },
      ],
      flow: "A learner taps the texted link, CloudFront serves the React site, and the Hono API on Lambda records watch coverage and quiz results in DynamoDB. Separately, an hourly EventBridge pass runs the scheduler, which applies the send rules and sends at most one reminder over SMS or email, carrying a short link back to the exact spot.",
    },
    outcomes: [
      {
        value: "3",
        numeric: 3,
        label: "Days, solo, to a working course",
        context: "From the first import on 29 Sep to the admin console on 1 Oct 2026, one engineer end to end.",
        source: SRC.courseReadme,
        projectSlug: "course-delivery",
      },
      {
        value: "8",
        numeric: 8,
        label: "Lessons, one question each",
        context: "The real chapters of the InnovateUS Civic AI course, about 34 minutes of video in all. Answers are checked on the server; the answer key is pending author sign-off before launch.",
        source: SRC.courseReadme,
        asOf: "1 Oct 2026",
        projectSlug: "course-delivery",
      },
      {
        value: "Pre-launch",
        label: "Status as of 3 Oct 2026",
        context: "Not public yet, and the repo records no launch date. Dev and prod stacks, alarms, a CI deploy and a runbook are in place. Still open before launch: re-file the carrier campaign with the current wording, confirm the monthly spend limit and get the answer key signed off.",
        source: SRC.courseReadme,
        projectSlug: "course-delivery",
      },
    ],
    stack: ["Hono", "TypeScript", "AWS Lambda", "AWS CDK", "DynamoDB", "EventBridge", "End User Messaging SMS", "SES", "CloudFront", "React", "Vite", "Vitest", "Cloudflare Turnstile", "GitHub Actions"],
    links: [{ label: "CivicAI Course videos (Vimeo showcase)", href: "https://vimeo.com/showcase/11896761", kind: "video" }],
    media: [
      {
        src: "/stills/course-delivery/01.jpg",
        alt: "A phone showing a text thread from InnovateUS. A sign-in code text sits above a reminder text saying the next CivicAI lesson, 3 of 8, is ready, with a link and Reply STOP to opt out.",
        kind: "image",
        width: 1600,
        height: 900,
        caption: "The reminder text: one segment, a link on the course's own domain, STOP honored. Sample name and link address.",
      },
      {
        src: "/stills/course-delivery/02.jpg",
        alt: "The lesson page on a phone: Lesson 3 video player, a gold progress meter reading 38 percent watched, and a notice that the learner skipped 1:10 to 1:40.",
        kind: "image",
        width: 1600,
        height: 900,
        caption: "Skipping ahead does not count: the question unlocks only after the video has really been watched. Sample progress.",
      },
      {
        src: "/stills/course-delivery/03.jpg",
        alt: "The one-question quiz on a phone for lesson 3, with four answer choices and option B marked Correct in green.",
        kind: "image",
        width: 1600,
        height: 900,
        caption: "One question per lesson, graded on the server. The question and options are the real lesson 3 content.",
      },
    ],
  },
  {
    slug: "arc-control-mcp",
    ownership: "sole",
    headlines: {
      problem: "The Chrome MCP server can’t be pointed at Arc.",
      built: "50 tools that let an agent use the browser I’m signed in to, in a window of its own.",
      flows: "A tool call goes in, Apple Events run it, the page comes back.",
      outcomes: "Fifty tools, published on npm.",
    },
    film: {
      src: "/films/arc-control-mcp.mp4",
      poster: "/films/arc-control-mcp.jpg",
      thumb: "/films/arc-control-mcp-thumb.jpg",
      thumb43: "/films/arc-control-mcp-thumb-43.jpg",
      vertical: { src: "/films/arc-control-mcp-vertical.mp4", poster: "/films/arc-control-mcp-vertical.jpg" },
      title: "arc-control-mcp launch film",
      transcript: FILM_TRANSCRIPTS["arc-control-mcp"],
    },
    name: "arc-control-mcp",
    tagline: "An MCP server that lets agents drive the Arc browser.",
    year: "2026",
    role: "Creator",
    owned: "Sole creator: all 50 tools, the rule that an agent never touches the tab or window I am using, and the CI and npm release.",
    featured: true,
    category: "tool",
    accent: "#8B5CF6",
    problem:
      "The bundled Chrome MCP server cannot be pointed at Arc, and Arc’s scripting dictionary differs from Chrome’s in exactly the places that matter.",
    approach: [
      "50 tools in twelve modules read pages, click, fill forms and run JavaScript over Apple Events, using the browser I am already signed in to. A page snapshot gives every element a ref the agent can act on, so it never guesses selectors.",
      "An optional DevTools engine adds real clicks and typing that sites treat as a person, screenshots of background tabs, and console and network logs.",
      "Agent tabs live in one window of their own on my second display, anything that could move focus waits until I stop typing, and failures are reported as failures, never as a success that did not happen.",
      "Two runtime dependencies (the MCP SDK and Zod), no build step, CI, and a changelog and security policy.",
    ],
    architecture: {
      nodes: ["AI agent", "MCP client", "arc-control-mcp", "Apple Events or DevTools", "Arc", "Agent window"],
      flow: "An agent calls a tool over MCP. The server runs it through Apple Events, or the DevTools engine for real input and screenshots, in a tab inside the agent’s own window, and the result goes back to the agent.",
    },
    outcomes: [
      {
        value: "50",
        numeric: 50,
        label: "Tools",
        context: "In twelve modules, as of version 0.4.0.",
        source: REPO.arcReadme,
        asOf: "5 Oct 2026",
        projectSlug: "arc-control-mcp",
      },
      {
        value: "35",
        numeric: 35,
        label: "Test files",
        context: "Cover the tool schemas, argument validation, the agent window and focus guard, the DevTools engine against a real Chromium, and live runs against Arc. There is no benchmark of agent task completion.",
        source: REPO.arcTests,
        projectSlug: "arc-control-mcp",
      },
      {
        value: "100",
        numeric: 100,
        label: "npm downloads, last month",
        context: "Month ending October 1, 2026. Registry counts include automated installs.",
        source: SRC.arcNpm,
        projectSlug: "arc-control-mcp",
      },
    ],
    stack: ["Node.js", "MCP SDK", "Zod", "JXA", "Apple Events", "GitHub Actions"],
    links: [
      { label: "GitHub", href: "https://github.com/DB-25/arc-control-mcp", kind: "code" },
      { label: "npm", href: "https://www.npmjs.com/package/arc-control-mcp", kind: "code" },
    ],
    media: [
      {
        src: "/stills/arc-control-mcp/01.jpg",
        alt: "A frame from the arc-control-mcp film. On the left, an agent transcript calls arc_status and open_url with the message previous selection restored. On the right, the Arc window keeps the user's tab selected while the agent's page loads in a background tab in a separate Agent space.",
        kind: "image",
        width: 1600,
        height: 798,
        caption: "The agent opens its own tab and the tab you are reading stays selected. A frame from the launch film; the pages are illustrative stand-ins.",
      },
      {
        src: "/stills/arc-control-mcp/02.jpg",
        alt: "A frame from the arc-control-mcp film after the agent has filled and submitted a contact form. The transcript lists get_page_content, two fill calls and a click, and the Agent space tab shows the form with a green Sent button.",
        kind: "image",
        width: 1600,
        height: 788,
        caption: "Read the form, fill two fields, click Send, all in a background tab. A frame from the launch film; the form and the name and email are illustrative.",
      },
      {
        src: "/stills/arc-control-mcp/03.jpg",
        alt: "The arc-control-mcp tool list from the film, with the count at 26 and tool names grouped by module: tabs, navigation, content, interaction, spaces and scripting.",
        kind: "image",
        width: 1600,
        height: 796,
        caption: "The 26 tools of version 0.3, as shown in the launch film; 0.4.0 has 50.",
      },
    ],
  },
  {
    slug: "voice-survey-agent",
    compact: true,
    name: "Voice Survey Agent",
    tagline: "The prototype that became Public Voice.",
    year: "2025",
    role: "Creator",
    featured: false,
    category: "lab",
    accent: "#7C5CFF",
    problem: "Could a short voice conversation replace a text box for workshop follow-up surveys?",
    approach: [
      "A Next.js app that runs a follow-up survey over OpenAI’s realtime voice API, with multiple choice and long-text questions and progress tracking.",
      "It answered the question, then the idea moved into Public Voice with privacy, dashboards and exports.",
    ],
    outcomes: [
      {
        value: "3 days",
        label: "First commit to last push",
        context: "Created July 15, 2025, last pushed July 18, 2025.",
        source: "https://github.com/DB-25/voice-based-survey-agent",
        projectSlug: "voice-survey-agent",
      },
    ],
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "OpenAI Realtime API"],
    links: [{ label: "GitHub", href: "https://github.com/DB-25/voice-based-survey-agent", kind: "code" }],
    media: [],
  },
  {
    slug: "vedira",
    compact: true,
    name: "Vedira",
    tagline: "A Flutter app for AI‑generated lessons.",
    year: "2025",
    role: "Mobile developer",
    featured: false,
    category: "mobile",
    accent: "#F0997B",
    problem: "People who want to learn something specific get generic courses.",
    approach: [
      "A cross-platform Flutter front end for personalized, scheduled AI-generated lessons.",
      "It talks to a serverless AWS Lambda backend written by a teammate, Rudra Sett.",
    ],
    outcomes: [
      {
        value: "2",
        numeric: 2,
        label: "Platforms",
        context: "iOS through TestFlight and Android through APK.",
        source: "https://github.com/DB-25/vedira",
        projectSlug: "vedira",
      },
    ],
    stack: ["Flutter", "Dart", "AWS Lambda"],
    links: [{ label: "GitHub", href: "https://github.com/DB-25/vedira", kind: "code" }],
    media: [],
  },
  {
    slug: "plastic-usage-classification",
    compact: true,
    name: "Plastic Usage Classification",
    tagline: "Computer vision coursework: sorting plastic into four categories from a photo.",
    year: "2023",
    role: "Author",
    org: "Northeastern University",
    featured: false,
    category: "lab",
    accent: "#5DCAA5",
    problem: "Can a model tell which of four plastic categories a product belongs to from its picture alone?",
    approach: [
      "PyTorch classifier with a ResNet50 backbone and an MLP head, tuned with Optuna.",
      "A Northeastern course project, built with one other contributor.",
    ],
    outcomes: [
      {
        value: "88.77%",
        numeric: 88.77,
        suffix: "%",
        label: "F1 score",
        context: "Across four plastic categories, from the product photo alone. The code is public.",
        source: SRC.interviewNotes,
        projectSlug: "plastic-usage-classification",
      },
    ],
    stack: ["Python", "PyTorch", "ResNet50", "Optuna"],
    links: [{ label: "GitHub", href: "https://github.com/DB-25/plastic_usage_classification", kind: "code" }],
    media: [],
  },
  {
    slug: "wesource-fraud-detection",
    compact: true,
    name: "Delivery Fraud Detector",
    tagline: "A small CNN for a delivery startup.",
    year: "2021 to 2022",
    role: "Machine Learning Intern",
    org: "We Source Company",
    featured: false,
    category: "lab",
    accent: "#85B7EB",
    problem: "A delivery company was losing money to fraudulent deliveries.",
    approach: [
      "I trained a CNN-based fraud detector and built two Flutter delivery apps in the same internship.",
    ],
    outcomes: [
      {
        value: "87.34%",
        numeric: 87.34,
        suffix: "%",
        label: "Accuracy",
        context: "At 103 ms latency.",
        source: SRC.resume,
        asOf: "Sep 2022",
        projectSlug: "wesource-fraud-detection",
      },
    ],
    stack: ["Python", "TensorFlow", "Flutter"],
    links: [],
    media: [],
  },
];
