import type { Recognition } from "./types";

export const recognition: Recognition[] = [
  {
    title: "Governor's Citation, InnovateMA",
    issuer: "Commonwealth of Massachusetts, signed by Gov. Maura Healey and Lt. Gov. Kimberley Driscoll",
    year: "2024",
    kind: "award",
    href: "/photos/governors-citation.jpg",
    note: "For developing and iterating on AI-based solutions to advance state services. Dated June 26, 2024.",
  },
  {
    title: "George Cronin Gold Award",
    issuer: "NASPO",
    year: "2025",
    kind: "award",
    href: "https://www.naspo.org/awards/george-cronin-awards/winners/2025/",
    note: "Won by Massachusetts OSD for its dual AI agents, ABE and One-L, built with the Burnes Center. I was part of the team behind them.",
  },
  {
    title: "Academic Collaboration Award",
    issuer: "NASPO",
    year: "2025",
    kind: "award",
    href: "https://www.naspo.org/awards/academic-collaboration-recognition/winners/",
    note: "For the OSD and Northeastern partnership behind the procurement AI tools.",
  },
  {
    title: "2nd place, VALORANT Champions Tour Hackathon",
    issuer: "AWS and Riot Games",
    year: "2024",
    kind: "award",
    href: "https://press.aboutamazon.com/2024/12/aws-and-riot-games-announce-the-winner-of-the-valorant-champions-tour-hackathon-esports-manager-challenge",
    note: "VCT Scout, with Aravind Dasarathy, Rudra Sett and Akshay Gunjur Surya Prakash. More than 3,200 participants.",
  },
  {
    title: "Best Cross-Regional Team Submission",
    issuer: "AWS and Riot Games",
    year: "2024",
    kind: "award",
    href: "https://press.aboutamazon.com/2024/12/aws-and-riot-games-announce-the-winner-of-the-valorant-champions-tour-hackathon-esports-manager-challenge",
  },
  {
    title: "AWS and Riot Games Announce the Winner of the VALORANT Champions Tour Hackathon",
    issuer: "Amazon Press Center",
    year: "2024",
    kind: "press",
    href: "https://press.aboutamazon.com/2024/12/aws-and-riot-games-announce-the-winner-of-the-valorant-champions-tour-hackathon-esports-manager-challenge",
  },
  {
    title: "Northeastern students are runners-up in global AWS hackathon",
    issuer: "Boston Business Journal",
    year: "2024",
    kind: "press",
    href: "https://www.bizjournals.com/boston/inno/stories/news/2024/12/13/northeastern-students-place-second-gloabl-esports.html",
  },
  {
    title: "How AI is changing esports: Northeastern students win big at Valorant challenge",
    issuer: "Northeastern Global News",
    year: "2025",
    kind: "press",
    href: "https://news.northeastern.edu/2025/02/04/valorant-hackathon-challenge-ai/",
  },
  {
    title: "Northeastern University Student Projects Improve Government With AI",
    issuer: "GovTech",
    year: "2024",
    kind: "press",
    href: "https://www.govtech.com/education/higher-ed/northeastern-university-student-projects-improve-government-with-ai",
    note: "Covers the InnovateMA projects, including the Generative AI Sandbox. Quotes me as Dhruv Kumar.",
  },
  {
    title: "Governor Healey meets with Northeastern students working on an AI project",
    issuer: "Massachusetts Governor's Office",
    year: "2024",
    kind: "press",
    href: "https://www.mass.gov/news/governor-healey-meets-with-northeastern-students-working-with-administration-on-ai-project-under-innovatema-partnership",
  },
  {
    title: "OSD's process innovations earn national recognition",
    issuer: "Mass.gov",
    year: "2025",
    kind: "press",
    href: "https://www.mass.gov/news/osds-process-innovations-earn-national-recognition",
  },
  {
    title: "Unboxing the prompt: how community feedback helped us build better AI",
    issuer: "Reboot Democracy",
    year: "2026",
    kind: "press",
    href: "https://rebootdemocracy.ai/blog/unboxing-the-prompt-how-community-feedback-and-ai-helped-us-build-better-ai-together",
    note: "My post (February 3, 2026) on how parents saw the A-IEP prompts and reshaped them.",
  },
  {
    title: "Presented the GenAI Sandbox work to Governor Healey",
    issuer: "InnovateMA, Massachusetts State House",
    year: "2024",
    kind: "talk",
    href: "https://www.mass.gov/news/governor-healey-meets-with-northeastern-students-working-with-administration-on-ai-project-under-innovatema-partnership",
    note: "The AI for Impact co-op cohort showed its work to the Governor in June 2024.",
  },
  {
    title: "AI for Coding: From Zero Experience to a Working Website",
    issuer: "InnovateUS Prompting Lab",
    year: "2026",
    kind: "talk",
    href: "https://innovate-us.org/ai-for-coding-from-zero-experience-to-a-working-website",
    note: "I taught this free 45 minute workshop on March 27, 2026. Participants prompted AI step by step to build a working website with no coding background.",
  },
  {
    title: "Prompting Lab Office Hours: Bring your AI Questions",
    issuer: "InnovateUS Prompting Lab",
    year: "2026",
    kind: "talk",
    href: "https://innovate-us.org/prompting-lab-office-hours-bring-you-ai-questions",
    note: "Live Q&A on April 10, 2026, following the coding workshop. InnovateUS lists me as a speaker.",
  },
  {
    title: "Project Spotlight: Co-Designing an AI Tool with Communities",
    issuer: "Reboot Democracy",
    year: "2026",
    kind: "press",
    href: "https://rebootdemocracy.ai/blog/project-spotlight-co-designing-with-communities",
    note: "Published October 1, 2026 on the A-IEP pilot in San Francisco, where more than 200 families took part.",
  },
  {
    title: "This is My Architecture: MassHealth Helper",
    issuer: "AWS, Boston Seaport",
    year: "2024",
    kind: "talk",
    href: "/photos/aws-talk.jpg",
    note: "I walked through the MassHealth Helper design using the Well-Architected principles at the AWS Boston Seaport office on September 6, 2024, alongside the AWS account team.",
  },
];
