import type { TimelineEntry } from "./types";

export const timeline: TimelineEntry[] = [
  {
    year: "2018",
    place: "Bangalore, India",
    title: "B.E. in Computer Science",
    org: "Acharya Institute of Technology",
    body: "Four years of computer science, and a lot of Flutter on the side. I graduated in July 2022.",
    kind: "education",
  },
  {
    year: "2020",
    place: "Bangalore, India (remote)",
    title: "First shipping jobs",
    org: "Fagnum, SM Creatives",
    body: "Remote Flutter internships while still in college: Fagnum from 2020 to 2021, SM Creatives in 2022.",
    kind: "work",
  },
  {
    year: "2021",
    place: "Bangalore, India (remote)",
    title: "Machine Learning Intern",
    org: "We Source Company",
    body: "Trained a CNN fraud detector for a delivery startup (87.34% accuracy, 103 ms) and built two Flutter delivery apps.",
    kind: "work",
  },
  {
    year: "2021",
    place: "Bangalore, India",
    title: "Software Engineer, Flutter",
    org: "Acharya Institutes",
    body: "Built the Acharya ERP app from design to deployment. It reached about 15,000 users and its store rating climbed from 1.2 to 4.5. I trained interns to take it over.",
    kind: "work",
  },
  {
    year: "2022",
    place: "Boston, MA",
    title: "Crossing oceans",
    org: "Northeastern University",
    body: "Moved to Boston for an M.S. in Artificial Intelligence at Khoury College. Computer vision, NLP and deep learning, with a 3.83 GPA.",
    kind: "education",
  },
  {
    year: "2024",
    place: "Boston, MA",
    title: "GenAI Product Development Co-op",
    org: "The Burnes Center for Social Change",
    body: "Joined the AI for Impact co-op in January. Built the Generative AI Sandbox for Massachusetts state employees with EOTSS and AWS, and wrote Smart Model, which picks the right model for each request.",
    kind: "work",
  },
  {
    year: "2024",
    place: "Boston, MA",
    title: "Governor's Citation",
    org: "Commonwealth of Massachusetts",
    body: "On June 26 Governor Healey and Lieutenant Governor Driscoll signed a citation recognizing my work in the InnovateMA program. GovTech quoted me a few days later.",
    kind: "milestone",
  },
  {
    year: "2024",
    place: "Boston, MA",
    title: "Full-time at the Burnes Center",
    org: "The Burnes Center for Social Change",
    body: "Stayed on after the co-op in July. The job grew from building tools to setting the technical direction for a program of student teams and public agencies.",
    kind: "work",
  },
  {
    year: "2024",
    place: "Remote",
    title: "Second place at the VALORANT hackathon",
    org: "AWS and Riot Games",
    body: "VCT Scout took second place and Best Cross-Regional Team Submission among more than 3,200 participants. I play the game, so I knew what a manager would ask.",
    kind: "milestone",
  },
  {
    year: "2024",
    place: "Boston, MA",
    title: "M.S. in Artificial Intelligence",
    org: "Northeastern University",
    body: "Graduated in December with a 3.83 GPA.",
    kind: "education",
  },
  {
    year: "2025",
    place: "Boston, MA",
    title: "Lead AI Engineer on A-IEP",
    org: "The Burnes Center for Social Change",
    body: "Took the AI-EP prototype to a production, open source platform that helps parents read their child's IEP in their own language. I made my first commit in February.",
    kind: "work",
  },
  {
    year: "2025",
    place: "Boston, MA",
    title: "Procurement AI wins at NASPO",
    org: "NASPO",
    body: "The ABE and One-L tools won the Cronin Gold Award and the Academic Collaboration Award for Massachusetts OSD and the Burnes Center. I was part of the team behind them.",
    kind: "milestone",
  },
  {
    year: "2026",
    place: "Boston, MA",
    title: "From shipping to measuring",
    org: "The Burnes Center for Social Change",
    body: "Public Voice and the Public Engagement Coach for InnovateUS. In July I audited A-IEP, found no automated check on accuracy, and started a synthetic IEP benchmark.",
    kind: "work",
  },
  {
    year: "2026",
    place: "Boston, MA",
    title: "arc-control-mcp ships",
    body: "Published an MCP server on npm so agents can drive the Arc browser I actually use. 26 tools, one dependency.",
    kind: "milestone",
  },
  {
    year: "2026",
    place: "Boston, MA",
    title: "Course Delivery SMS",
    org: "The Burnes Center for Social Change",
    body: "Started an 8-day, text-paced video course platform for InnovateUS. Sixty-five commits in the first three days.",
    kind: "work",
  },
  {
    year: "Always",
    place: "Boston, MA",
    title: "Off duty",
    body: "Black and purple everything. Valorant and CS2 on a PC I keep tweaking. Cooking Indian, Italian and Mexican vegetarian food. Pani puri is non-negotiable. Acadia National Park is the favorite trip.",
    kind: "personal",
  },
];
